### ISSUE TITLE
提示：请求失败，JSON返回码 103

### ISSUE THREAD

**Issue by tourze** [ScienJus/qqbot#3]
I, [2016-04-30 16:43:25#91447]  INFO -- : 请求失败，JSON返回码 103
I, [2016-04-30 16:43:26#91447]  INFO -- : 请求失败，JSON返回码 103
I, [2016-04-30 16:43:28#91447]  INFO -- : 请求失败，JSON返回码 103
I, [2016-04-30 16:43:29#91447]  INFO -- : 请求失败，JSON返回码 103
I, [2016-04-30 16:43:30#91447]  INFO -- : 请求失败，JSON返回码 103
I, [2016-04-30 16:43:32#91447]  INFO -- : 请求失败，JSON返回码 103
I, [2016-04-30 16:43:33#91447]  INFO -- : 请求失败，HTTP返回码 502

**Comment by ScienJus** [comment]
103错误需要先手动登录w.qq.com，然后再尝试使用软件。
